#!/bin/sh

main() {
	dir=~/.local/share/ffmpeg
	mon=":0.0+$(randr | awk -F '+' '{print $2","$3}')"
	opts="-c:v libx264 -r 60 -c:a flac -preset ultrafast"
	size="$(randr | cut -d '+' -f1)"
	title="$(date | awk 'OFS="-" {print $4,$3,$2,$1,$5}' | tr '[:upper:]' '[:lower:]')"

	if [ -n "$audio" -a -n "$display" ]; then
	    if [ ! -d $dir/Display ]; then
		mkdir -p $dir/Display
	    fi
		ffmpeg -n \
			-f alsa \
			-i default \
			-f x11grab \
			-s "$size" \
			-i "$monitor" \
			$opts \
			$dir/Display/ffrec-$title.mkv
	elif [ -n "$audio" ]; then
	    if [ ! -d $dir/Audio ]; then
		mkdir -p $dir/Audio
	    fi
		ffmpeg -n \
			-f alsa \
			-i default \
			$opts \
			$dir/Audio/ffrec-$title.flac
	elif [ -n "$display" ]; then
	    if [ ! -d $dir/Display ]; then
		mkdir -p $dir/Display
	    fi
		ffmpeg -n \
			-f x11grab \
			-s "$size" \
			-i "$monitor" \
			$opts \
			$dir/Display/ffrec-$title.mkv
	fi
}

randr() {
	xrandr |
		grep primary |
		cut -d ' ' -f4
}

parse_opts() {
    while [ $# -gt 0 ]; do
        key="$1"
        case $key in
        -a|--audio)
            audio=1
            shift
            ;;
        -d|--display)
            display=1
            shift
            ;;
	-ad|-da)
	    audio=1
	    display=1
	    shift
	    ;;
        *)
            shift
            ;;
        esac
    done
}

main "$@"
